In [25]:
import numpy as np 
import pandas as pd 

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [26]:
df = pd.read_csv('/home/lucky/Machine_Learning/datasets/train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [27]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [28]:
df.isna().sum()

Age         177
Pclass        0
SibSp         0
Parch         0
Survived      0
dtype: int64

In [29]:
df.dropna(inplace=True)

In [30]:
df.isna().sum()

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [31]:
X = df.iloc[:, 0:4]
y = df.iloc[:, -1]

In [32]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [33]:
np.mean(cross_val_score(LogisticRegression(), X,y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

## Applying Feature Construction

In [34]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [35]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [36]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num > 1 and num <= 4:
        #small family
        return 1
    else:
        #Big Family
        return 2

In [37]:
myfunc(4)

1

In [38]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [39]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [40]:
X

      Age  Pclass  SibSp  Parch  Family_size  Family_type
0    22.0       3      1      0            2            1
1    38.0       1      1      0            2            1
2    26.0       3      0      0            1            0
3    35.0       1      1      0            2            1
4    35.0       3      0      0            1            0
..    ...     ...    ...    ...          ...          ...
885  39.0       3      0      5            6            2
886  27.0       2      0      0            1            0
887  19.0       1      0      0            1            0
889  26.0       1      0      0            1            0
890  32.0       3      0      0            1            0

[714 rows x 6 columns]

In [41]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [42]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [44]:
np.mean(cross_val_score(LogisticRegression(), X, y, cv=20, scoring='accuracy'))

np.float64(0.7003174603174602)

## Feature Splitting

In [45]:
new_df = pd.read_csv('/home/lucky/Machine_Learning/datasets/train.csv')

In [46]:
new_df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [50]:
new_df['Title'] = new_df['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]

In [51]:
new_df[['Title','Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [54]:
new_df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [57]:
new_df['Is_Married'] = 0
new_df['Is_Married'].loc[new_df['Title'] == 'Mrs'] = 1

/tmp/ipykernel_3242436/1021663209.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new_df['Is_Married'].loc[new_df['Title'] == 'Mrs'] = 1
/tmp/ipykernel_3242436/1021663209.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Is_Married'].loc[new_df['Title'] == 'Mrs'] = 1

In [59]:
new_df['Is_Married']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_Married, Length: 891, dtype: int64

In [63]:
new_df[['Title', 'Is_Married']].sample(10)

     Title  Is_Married
307    Mrs           0
477     Mr           0
14    Miss           0
190    Mrs           0
442     Mr           0
700    Mrs           0
526   Miss           0
82    Miss           0
487     Mr           0
872     Mr           0