In [25]:
import numpy as np 
import pandas as pd 

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [26]:
df = pd.read_csv('/home/lucky/Machine_Learning/datasets/train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [27]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [28]:
df.isna().sum()

Age         177
Pclass        0
SibSp         0
Parch         0
Survived      0
dtype: int64

In [29]:
df.dropna(inplace=True)

In [30]:
df.isna().sum()

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [31]:
X = df.iloc[:, 0:4]
y = df.iloc[:, -1]

In [32]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [33]:
np.mean(cross_val_score(LogisticRegression(), X,y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

## Applying Feature Construction

In [34]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [35]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [36]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num > 1 and num <= 4:
        #small family
        return 1
    else:
        #Big Family
        return 2

In [37]:
myfunc(4)

1

In [38]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [39]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [40]:
X

      Age  Pclass  SibSp  Parch  Family_size  Family_type
0    22.0       3      1      0            2            1
1    38.0       1      1      0            2            1
2    26.0       3      0      0            1            0
3    35.0       1      1      0            2            1
4    35.0       3      0      0            1            0
..    ...     ...    ...    ...          ...          ...
885  39.0       3      0      5            6            2
886  27.0       2      0      0            1            0
887  19.0       1      0      0            1            0
889  26.0       1      0      0            1            0
890  32.0       3      0      0            1            0

[714 rows x 6 columns]

In [41]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [42]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [44]:
np.mean(cross_val_score(LogisticRegression(), X, y, cv=20, scoring='accuracy'))

np.float64(0.7003174603174602)