In [1]:
#sort_values

In [2]:
import pandas as pd
import numpy as np

movies = pd.read_csv('bollywood.csv',index_col="movie").squeeze()
movies.head()
type(movies)

/home/lucky/anaconda3/lib/python3.12/site-packages/pandas/core/computation/expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/lucky/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

pandas.Series

In [3]:
movies.tail()

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: str

In [4]:
vk = pd.read_csv('kohli_ipl.csv',index_col='match_no').squeeze()
type(vk)
# vk.head()

pandas.Series

In [5]:
type(vk)

pandas.Series

In [6]:
vk.sort_values()

match_no
87       0
211      0
207      0
206      0
91       0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [7]:
vk.sort_values(ascending=False)

match_no
128    113
126    109
123    108
164    100
120    100
      ...
93       0
211      0
130      0
8        0
135      0
Name: runs, Length: 215, dtype: int64

In [8]:
#sort_index

In [9]:
movies.sort_index(inplace=True)

In [10]:
movies

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: str

In [11]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

fruits = ["Apple", "Banana", "Orange", "Apple"]

encoded = encoder.fit_transform(fruits)

print(encoded)

/home/lucky/anaconda3/lib/python3.12/site-packages/sklearn/utils/_param_validation.py:14: UserWarning: A NumPy version >=2.0.0 and <2.8.0 is required for this version of SciPy (detected version 1.26.4)
  from scipy.sparse import csr_array, issparse
/home/lucky/anaconda3/lib/python3.12/site-packages/scipy/sparse/_sputils.py:17: FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.
  np.uintc, np.long, np.ulong, np.longlong, np.ulonglong,

AttributeError: module 'numpy' has no attribute 'long'

In [12]:
import pandas as pd

df = pd.DataFrame({
    "Color":["Red", "Blue", "Green", "Red"]
})

encoded = pd.get_dummies(df)

print(encoded)

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3       False        False       True

In [13]:
movies

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: str

In [14]:
homeprice = pd.read_csv('/home/lucky/Machine_Learning/working-with-data/homeprices_var.csv',usecols=['area','price'])

homeprice

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  595000
4  4000  760000

In [18]:
pd.read_csv('/home/lucky/Machine_Learning/working-with-data/bollywood.csv',skiprows=[1,2])

                                     movie                  lead
0     The Accidental Prime Minister (film)           Anupam Kher
1                          Why Cheat India         Emraan Hashmi
2                          Evening Shadows      Mona Ambegaonkar
3                              Soni (film)  Geetika Vidya Ohlyan
4                            Fraud Saiyaan          Arshad Warsi
...                                    ...                   ...
1493                Hum Tumhare Hain Sanam        Shah Rukh Khan
1494                   Aankhen (2002 film)      Amitabh Bachchan
1495                       Saathiya (film)          Vivek Oberoi
1496                        Company (film)            Ajay Devgn
1497                  Awara Paagal Deewana          Akshay Kumar

[1498 rows x 2 columns]